// Generated by Blaze Transpiler
// Current Date and Time (UTC): 2024-12-11 21:14:14
package main

import (
	"net/http"
	"io"
	"fmt"
)

func main() {
	url := "http://letsgosky.social"
	var err error
	// this is a commment, this gets sent to the transpiled version too
	response , err := http.Get(url)
	body , err := io.ReadAll(response.Body)
	fmt.Print("Response Status: " + response.Status)
	fmt.Print("Response Body: " + string(body))
	if err != nil {
	fmt.Print("Error: " + err.Error())
	}
}
