// Generated by Blaze Transpiler
// Current Date and Time (UTC): 2024-12-11 20:26:47
package main

import (
	"fmt"
	"net/http"
	"io"
)

func main() {
	url := "http://letsgosky.social"
	var err error
	response , err := http.Get(url)
	body , err := io.ReadAll(response.Body)
	fmt.Print("Response Status: " + response.Status)
	fmt.Print("Response Body: " + string(body))
	if err != nil {
	fmt.Print("Error: " + err.Error())
	}
}
